<?php
/**
 *Configuração do WeGIA
*/
define( 'APP_TIMEZONE', 'America/Sao_Paulo');
define( 'BKP_DIR', '/var/www/bkpWeGIA');
define( 'BACKUP_SIGNING_KEY_FILE', BKP_DIR . '/.backup_signing_private.pem');
define( 'DB_NAME', 'wegia' );
define( 'DB_USER', 'wegiauser' );
define( 'DB_PASSWORD', 'senha' );
define( 'DB_HOST', 'localhost');
define( 'DB_CHARSET', 'utf8');
define( 'ROOT',dirname(__FILE__));
define( 'WWW', 'https://demo.wegia.org/');

define( 'DEV_MODE', 'off');

/**
 *Configuração da API
*/

define('API_BASE_URL', 'https://demo.wegia.org/api/');
define('JWT_SECRET', 'your_jwt_secret_key_here');
define('ENV_APP', 'production'); //define('ENV_APP', 'development');

//Separe as origens permitidas com o caractere ","
define('CORS_ORIGIN', 'https://demo.wegia.org,http://localhost');
