<?php
/**
 *Configuração do WEGIA
*/
define( 'APP_TIMEZONE', 'America/Sao_Paulo');
define( 'BKP_DIR', '/var/www/bkpWeGIA');
define( 'BACKUP_SIGNING_KEY_FILE', BKP_DIR . '/.backup_signing_private.pem');
define( 'DB_NAME', 'wegia' );
define( 'DB_USER', 'wegiauser' );
define( 'DB_PASSWORD', 'senha' );
define( 'DB_HOST', 'localhost');
define( 'DB_CHARSET', 'utf8');
define( 'ROOT',dirname(__FILE__));
define( 'WWW', 'https://demo.wegia.org/');

define( 'DEV_MODE', 'off');
